### ISSUE TITLE
doesn't work with translatable on 3.1

### ISSUE THREAD

**Issue by dacar** [silverstripe-labs/silverstripe-dms#19]
Hi, on SS 3.1 with the translatable module you have to enter the locale to the URL manualy to make the fileupload work properly. E.g. &locale=en_GB

The link for the "add" button looks like:
http://www.XXX.de/admin/pages/adddocument?ID=45

http://www.XXX.de/admin/pages/adddocument?ID=45&locale=en_GB

Greetings, Carsten.

**Comment by DrMartinGonzo** [comment]
For me the add button works and is formatted this way : 

http://www.XXX.de/admin/pages/adddocument/?Locale=en_GB&ID=61

The back button didn't work though,
I replaced line 166 in DMSDocumentAddController.php with : 

`return Controller::join_links(singleton('CMSPagesController')->Link(), 'edit/show/'.$pageID);`

instead of:

`return singleton('CMSPagesController')->Link().'edit/show/'.$pageID;`

**Comment by xini** [comment]
can be closed, #82 merged.
